# Generated by Django 5.2.13 on 2026-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский')], default='uz', max_length=2, verbose_name='Til'),
        ),
    ]
