# Generated by Django 5.2.13 on 2026-04-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chatmessage'),
        ('users', '0002_telegramuser_language'),
    ]

    operations = [
    ]
